import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../assets/css/style.css";
import "../assets/css/animation.css";
import "../assets/css/responsive.css";

// 1. Brackets {} hatao aur default import karo
import faveicon from "../assets/images/favicon-32x32.png"; 

import Navbar from "@/component/Navbar/Navbar";
import Login from "@/component/Login/Login";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "mega-resources-spp",
  description: "Generated by create next app",
  icons: {
    // 2. faveicon.src use karo taake URL milay
    icon: faveicon.src, 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}